
[workspace]
members = [
  "wumbo/cli",
  "wumbo/program",
  "spl-token-bonding/cli",
  "spl-token-bonding/program",
  "spl-token-staking/program"
]
exclude = []
[profile.dev]
split-debuginfo = "unpacked"